server:
  port: 8090
spring:
  application:
    name: user-account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_account_db
    username: root
    password: root
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mdsaquibansari24@gmail.com
    password: tzts jcuh hmfu wvnv
    properties:
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
  thymeleaf:
    prefix: file:///${eXtrade.template.dir}

logging:                     #transaction logging info will logged ,this is the property
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: /var/log/xtrade-user-account-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 100GB

springdoc:       #automatically it starts generating documentation (swagger)
  api-docs:
    enabled: true
    path: /apidoc               #path of the documentation is, for any service if i type this  it starts documentation
  swagger-ui:                  # i want to see the documentation
    path: /swaggerui.html      # swagger will be visible ,api documentation will come, we can import api doc to postman
    enabled: true              #if u want documentation to be really generated,we need to write api annotation

eXtrade:
  template:
    dir: ${user.home}/projectspace/templates/
  customer:
    weblink: http://localhost:8088/
